"""add_booking_notification_and_scheduled_task_tables

Revision ID: 636b46328624
Revises: 
Create Date: 2025-10-09 14:51:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636b46328624'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create booking_notifications table
    op.create_table('booking_notifications',
        sa.Column('id', sa.Integer(), nullable=False, comment='通知ID'),
        sa.Column('booking_id', sa.Integer(), nullable=False, comment='预订ID'),
        sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
        sa.Column('notification_type', sa.String(length=50), nullable=False, comment='通知类型'),
        sa.Column('title', sa.String(length=100), nullable=False, comment='通知标题'),
        sa.Column('content', sa.Text(), nullable=False, comment='通知内容'),
        sa.Column('status', sa.String(length=20), nullable=True, comment='通知状态'),
        sa.Column('send_time', sa.DateTime(), nullable=True, comment='发送时间'),
        sa.Column('retry_count', sa.Integer(), nullable=True, comment='重试次数'),
        sa.Column('max_retries', sa.Integer(), nullable=True, comment='最大重试次数'),
        sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
        sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
        sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
        sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        comment='预订通知表'
    )
    op.create_index('idx_notification_booking_id', 'booking_notifications', ['booking_id'], unique=False)
    op.create_index('idx_notification_created_at', 'booking_notifications', ['created_at'], unique=False)
    op.create_index('idx_notification_deleted', 'booking_notifications', ['is_deleted'], unique=False)
    op.create_index('idx_notification_status', 'booking_notifications', ['status'], unique=False)
    op.create_index('idx_notification_type', 'booking_notifications', ['notification_type'], unique=False)
    op.create_index('idx_notification_user_id', 'booking_notifications', ['user_id'], unique=False)
    
    # Create scheduled_tasks table
    op.create_table('scheduled_tasks',
        sa.Column('id', sa.Integer(), nullable=False, comment='任务ID'),
        sa.Column('task_id', sa.String(length=100), nullable=False, comment='任务唯一标识'),
        sa.Column('task_type', sa.String(length=50), nullable=False, comment='任务类型'),
        sa.Column('related_type', sa.String(length=50), nullable=True, comment='关联类型'),
        sa.Column('related_id', sa.Integer(), nullable=True, comment='关联ID'),
        sa.Column('title', sa.String(length=100), nullable=False, comment='任务标题'),
        sa.Column('description', sa.Text(), nullable=True, comment='任务描述'),
        sa.Column('scheduled_time', sa.DateTime(), nullable=False, comment='计划执行时间'),
        sa.Column('executed_time', sa.DateTime(), nullable=True, comment='实际执行时间'),
        sa.Column('status', sa.String(length=20), nullable=True, comment='任务状态'),
        sa.Column('result', sa.Text(), nullable=True, comment='执行结果'),
        sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
        sa.Column('retry_count', sa.Integer(), nullable=True, comment='重试次数'),
        sa.Column('max_retries', sa.Integer(), nullable=True, comment='最大重试次数'),
        sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
        sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('task_id'),
        comment='定时任务表'
    )
    op.create_index('idx_task_deleted', 'scheduled_tasks', ['is_deleted'], unique=False)
    op.create_index('idx_task_related', 'scheduled_tasks', ['related_type', 'related_id'], unique=False)
    op.create_index('idx_task_scheduled_time', 'scheduled_tasks', ['scheduled_time'], unique=False)
    op.create_index('idx_task_status', 'scheduled_tasks', ['status'], unique=False)
    op.create_index('idx_task_task_id', 'scheduled_tasks', ['task_id'], unique=False)
    op.create_index('idx_task_type', 'scheduled_tasks', ['task_type'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_type', table_name='scheduled_tasks')
    op.drop_index('idx_task_task_id', table_name='scheduled_tasks')
    op.drop_index('idx_task_status', table_name='scheduled_tasks')
    op.drop_index('idx_task_scheduled_time', table_name='scheduled_tasks')
    op.drop_index('idx_task_related', table_name='scheduled_tasks')
    op.drop_index('idx_task_deleted', table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index('idx_notification_user_id', table_name='booking_notifications')
    op.drop_index('idx_notification_type', table_name='booking_notifications')
    op.drop_index('idx_notification_status', table_name='booking_notifications')
    op.drop_index('idx_notification_deleted', table_name='booking_notifications')
    op.drop_index('idx_notification_created_at', table_name='booking_notifications')
    op.drop_index('idx_notification_booking_id', table_name='booking_notifications')
    op.drop_table('booking_notifications')
    # ### end Alembic commands ###